// Generated by CoffeeScript 1.6.3
(function() {
  var MATextInput,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MATextInput = (function() {
    MATextInput.prototype._domRef = null;

    MATextInput.prototype._default = '';

    function MATextInput() {
      this.get = __bind(this.get, this);
      this.reset = __bind(this.reset, this);
      this.set = __bind(this.set, this);
      if (arguments.length) {
        this.initWithJQ.apply(this, arguments);
      }
    }

    MATextInput.prototype.initWithJQ = function(jq) {
      return this._domRef = jq;
    };

    MATextInput.prototype.set = function(text) {
      return this._domRef.value = text;
    };

    MATextInput.prototype.reset = function() {
      return this._domRef.value = this._default;
    };

    MATextInput.prototype.get = function() {
      return this._domRef.value;
    };

    return MATextInput;

  })();

}).call(this);
