// Generated by CoffeeScript 1.6.3
(function() {
  var MATemplate,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  MATemplate = (function() {
    /*
    	This is a template for a form. It dictates which fields should be automated, and what buttons should be created.
    	It should also have a way of detecting whether it's appropriate for the current page.
    */

    MATemplate.prototype._fields = null;

    function MATemplate() {
      this.get = __bind(this.get, this);
      this.reset = __bind(this.reset, this);
      this.set = __bind(this.set, this);
      if (arguments.length) {
        this.initWithJQ.apply(this, arguments);
      }
    }

    MATemplate.prototype.initWithJQ = function(jq) {
      return this._domRef = jq;
    };

    MATemplate.prototype.set = function(text) {
      return this._domRef.value = text;
    };

    MATemplate.prototype.reset = function() {
      return this._domRef.value = this._default;
    };

    MATemplate.prototype.get = function() {
      return this._domRef.value;
    };

    return MATemplate;

  })();

}).call(this);
